# Taken from here:
# https://github.com/alphapapa/helm-org-rifle/blob/94cb602d6373229c88126a5888f03f4b538f0771/.travis.yml
addons:
  apt:
    packages:
    - git

before_install:
  - sudo apt-get -yq update
  - sudo apt-get -yq install git

  - git clone https://github.com/rejeep/evm.git $HOME/.evm
  - export PATH=$HOME/.evm/bin:$PATH

  - evm config path /tmp
  - evm install $EVM_EMACS --use --skip

  # Use cask to install development dependencies
  - curl -fsSkL https://raw.github.com/cask/cask/master/go | python
  - export PATH=$HOME/.cask/bin:$PATH
  - cask

env:
  - EVM_EMACS=emacs-24.4-travis
  - EVM_EMACS=emacs-24.5-travis
  - EVM_EMACS=emacs-25.1-travis
  - EVM_EMACS=emacs-25.2-travis
script:
  - ln -s tests/fixtures/ fixtures
  - cask exec emacs --batch -l ert -l org-wild-notifier.el -l tests/org-wild-notifier-tests.el  -l org-wild-notifier.el -f ert-run-tests-batch-and-exit

notifications:
email: false
